# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'Scribe' do

    pod 'Atlas'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    
end

